export default [
    {
        "id": "secret-garden",
        "username": "SecretGarden",
        "joined": "1996-12-31",
        
    },
    {
        "id": "stillwaters",
        "username": "StillWaters",
        "title": "Pond Watcher",
        "location": "Somewhere nearby",
        "oshis": "Shinri",
        "age": "Old enough to remember",
        "hobbies": "Reading threads, replying late, preparing for the unavoidable apocalypse",
        "joined": "1996-10-04",

    },
    {
        "id": "ladylake",
        "username": "LadyOfTheLake",
        "title": "Matron of the deep",
        "location": "The oldest stone by the pond",
        "oshis": "Shinri",
        "age": "Classified",
        "hobbies": "Cooking (lore and food), midnight walks and photographic cryptids",
        "joined": "1996-10-04",

    },
    {
        "id": "neverscared",
        "username": "NeverScared",
        "title": "King of Horror Games",
        "location": "In Shinri's walls",
        "oshis": "Shinri",
        "age": "Ancient",
        "hobbies": "Playing Games, Knitting, Going to the Movies",
        "joined": "1996-12-31",

    },
    {
        "id": "ripplepoppop",
        "username": "RipplePopPop",
        "title": "Draft #3",
        "location": "Near the lilypads",
        "oshis": "Shinri, Jurard, Flayon",
        "age": "14",
        "hobbies": "Writing fanfics, anime, horror, number 1 BlueHedgehog fan",
        "joined": "1996-10-04",
    },
    {
        "id": "dewdrop",
        "username": "DewDrop",
        "title": "",
        "location": "on a morning walk",
        "oshis": "Shinri",
        "age": "-",
        "hobbies": "Hunting cryptids, lazy afternoon naps, cuddles",
        "joined": "1996-10-04",

    },
    { 
        "id": "missing-koi",
        "username": "MissingKoi",
        "title": "Pattern analyst",
        "location": "Below the surface",
        "oshis": "Shinri, Ruze",
        "age": "Last seen yesterday",
        "hobbies": "Lurking, Late-Night Posting, Keeping Notes, Conspiracy Theories, Moképon",
        "joined": "1996-10-04",
    },
    { 
        "id": "koi-mod",
        "username": "guardian of the pond",
        "title": "Moderator",
        "location": "here",
        "oshis": "Shinri",
        "hobbies": "Observing...",
        "joined": "2023-02-01",
    },
    { 
        "id": "koinspiratorial",
        "username": "Koinspiratorial",
        "title": "Paredolia Master",
        "location": "You'll Never Find Me!",
        "oshis": "Shinri, Octavio",
        "age": "I'll Never Tell!",
        "hobbies": "Conspiracy Theories, Watching Streams, Karaoke",
        "joined": "1996-10-04",
    },
    { 
        "id": "beegfeesh",
        "username": "BEEGFEESH",
        "title": "The Beegest Fish!",
        "location": "The Koi Pond",
        "oshis": "Shinri, Axel",
        "age": "Not too beeg, not too small",
        "hobbies": "Swimming, Watching Streams, Memeing",
        "joined": "1996-10-04",
    },
    {
        "id": "user",
        "username": "???",
        "joined": "1970-1-1",
    }
]
